name: pull-request-commit
on:
  pull_request:
    branches: ['main']
jobs:
  build:
    strategy:
      matrix:
        pyver: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest', 'windows-latest']
    uses: ./.github/workflows/workflow-build.yml
    with:
      pyver: ${{ matrix.pyver }}
      os: ${{ matrix.os }}
  test:
    needs: [build]
    strategy:
      matrix:
        pyver: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest', 'windows-latest']
    uses: ./.github/workflows/workflow-test.yml
    with:
      pyver: ${{ matrix.pyver }}
      os: ${{ matrix.os }}
  pages:
    needs: [build]
    strategy:
      matrix:
        pyver: ['3.9']
        os: ['ubuntu-latest']
    uses: ./.github/workflows/workflow-pages.yml
    with:
      pyver: ${{ matrix.pyver }}
      os: ${{ matrix.os }}